# Generated by Django 4.2.7 on 2024-01-10 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('bio', models.TextField(default=None)),
                ('email', models.EmailField(default=None, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Quantity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.CharField(max_length=100)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RecipesApp.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('recipe_name', models.CharField(max_length=300)),
                ('prep_time', models.IntegerField()),
                ('cook_time', models.IntegerField()),
                ('total_time', models.IntegerField()),
                ('servings', models.IntegerField()),
                ('difficulty', models.CharField(default=None, max_length=300)),
                ('instructions', models.JSONField(default=list)),
                ('tips', models.JSONField(default=list)),
                ('author_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RecipeAuthorEmail', to='RecipesApp.author')),
                ('author_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RecipeAuthorName', to='RecipesApp.author')),
                ('ingredients', models.ManyToManyField(through='RecipesApp.Quantity', to='RecipesApp.ingredient')),
                ('tags', models.ManyToManyField(to='RecipesApp.tags')),
            ],
        ),
        migrations.AddField(
            model_name='quantity',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RecipesApp.recipe'),
        ),
    ]
