# Generated by Django 4.2.7 on 2024-01-10 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RecipesApp', '0002_rename_tags_tag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Units',
            new_name='Unit',
        ),
    ]
