# Generated by Django 4.2.7 on 2023-12-18 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipesApp', '0003_recipe_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.CharField(default=None, max_length=1000),
        ),
    ]
