# Generated by Django 4.2.7 on 2024-01-17 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RecipesApp', '0003_rename_units_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='quantity',
            name='unit',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='RecipesApp.unit'),
        ),
    ]
