# Generated by Django 4.2.7 on 2024-01-17 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RecipesApp', '0004_quantity_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantity',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RecipesApp.unit'),
        ),
    ]
