# Generated by Django 4.2.7 on 2024-01-17 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipesApp', '0005_alter_quantity_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantity',
            name='quantity',
            field=models.FloatField(),
        ),
    ]
