# Generated by Django 4.2.7 on 2023-12-24 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RecipesApp', '0007_alter_author_id_alter_category_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='category',
            new_name='categorys',
        ),
    ]
